site_name: ADMM Optimizer
site_description: An Alternating Direction Method of Multipliers (ADMM) optimizer for Neural Networks (NNs) and Spiking Neural Networks (SNNs).
theme:
  name: material
  palette:
    # Set a clean toggle for light/dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs # Top navigation bar
    - navigation.indexes # Clickable section headers

# The structure of your website
nav:
  - Home: index.md
  - Tutorials:
    - Getting Started: tutorials/getting_started.md
  - Theory:
    - Motivation: theory/motivation.md
  - API Reference:
    - Manager: api/manager.md
    - Base Layer Logic: api/base_layer.md
    - Affine Layer Logic: api/affine_layer.md
    - Spiking Logic: api/spiking_mixin.md
    - Layers: api/layers.md
    - Covariance Handler: api/covariance_handler.md
    - State Handler: api/state_handler.md
    - Activation functions: api/activation_functions.md
    - Loss Functions: api/loss_functions.md
    - Pooling Operations: api/pooling.md
    - Metrics: api/metrics.md
    - Initializers: api/initializers.md
    - Scheduler: api/scheduler.md
    - Dataclasses: api/dataclasses.md
    - Functional: 
      - Weights Solvers: api/weights_solvers.md
      - Activation Update Solvers: api/a_update_solvers.md
      - Utils: api/utils.md
      - FFT-Utils: api/fft_utils.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            members_order: source
            filters: []

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

