[project]
name = "snn-admm-optimizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "matplotlib>=3.10.1",
    "numpy>=1.26.0",
    "pandas",
    "safetensors>=0.7.0",
    "snntorch>=0.9.4",
    "tonic>=1.6.0",
    "torch==2.4.0",
    "torchvision==0.19.0",
]

# Explicitly route PyTorch to prevent CUDA version mismatches
[[tool.uv.index]]
name = "pytorch-cu118"
url = "https://download.pytorch.org/whl/cu118"
explicit = true

[tool.uv.sources]
torch = [
  { index = "pytorch-cu118", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
  { index = "pytorch-cu118", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]

[dependency-groups]
dev = [
    "mkdocs<2.0.0",
    "mkdocs-material>=9.7.6",
    "mkdocstrings[python]>=1.0.4",
    "psutil>=7.2.2",
    "pymdown-extensions>=10.21.2",
    "pytest>=9.0.3",
    "ruff>=0.15.12",
]

[tool.pytest.ini_options]
filterwarnings = [
    # This ignores any warning that contains the phrase "Using circular padding without FFTs"
    "ignore:.*Using circular padding without FFTs.*:UserWarning",
]