[static]
; model= spiking-conv
batch_size = 30
epochs = 50
warming_iters = 15
gamma = 0.1
beta = 1.0
n_timesteps = 150
deltas = 0.95
thetas = 0.3
hidden_dims=100
hidden_channels=2
kernel_size=5
padding=2
stride=2
init = zeros
bias=False 
; train_method = unrolled-sequential
use_double=False

[grid]
  model= spiking-conv, spiking-linear
; batch_size = 50
; epochs = 20
; warming_iters = 6
; gamma = 0.1
; beta = 1.0
; n_timesteps = 150
; deltas = 0.95
; thetas = 0.3
; hidden_dims=100
; hidden_channels=4
; kernel_size=5
; padding=2
; stride=2
; init = zeros, xavier
; bias=False 
train_method = vectorized, unrolled-random, unrolled-sequential, hybrid-random, hybrid-sequential
; use_double=False