[config]
seed= 8281003564
#OPTIONS ARE: linear, conv, spiking-linear, spiking-conv
model = spiking-conv
#OPTIONS ARE: 2,3 (For non spiking also 5)
layers = 3

batch_size = 200
epochs = 100
warming_iters = 30

beta = 0.1
rho = 1

n_timesteps = 150
deltas = 0.95
thetas = 1

hidden_dims = 512

hidden_channels = 8
kernel_size = 5
padding = 2
stride = 1

# OPTIONS ARE: "zeros-rng", "zeros", "xavier","zeros-pass"
init = zeros
#OPTIONS ARE: "vectorized", "unrolled-random", "unrolled-sequential", "decoupled-random", "decoupled-sequential"
train_method =  decoupled-sequential

bias = False
use_double = False
use_fft = True
padding_mode = circular
