[affine]
# ================= GENERAL PARAMS ======================
batch_size = 5 
epochs = 20
warming_iters = 3

gamma = 0.1  
beta = 1

# ============== SPIKING PARAMS ==================
n_timesteps = 150
deltas = 0.95
thetas = 1

# =================== LINEAR PARAMS =====================
hidden_dims=20

################################################
#This allows to use double precision.
use_double=True
