[general]

section=admm_affine_128

[admm_affine_128]
# ========================================
# 1. Global Training Params
# ========================================
batch_size = 128
epochs = 10
warming_iters = 5
n_timesteps = 150

# ========================================
# 2. Shared Params
# ========================================

deltas = 0.95
thetas = 0.15

# ========================================
# 3. Linear Params
# ========================================
hidden_dims=516

linear_gamma = 0.01
linear_beta = 0.01

linear_scale = 1.0
linear_scale_last_layer = 0.01


# ========================================
# 4. Conv Params
# ========================================
hidden_channels=16

conv_gamma = 0.1
conv_beta = 0.1

conv_scale = 3.0
conv_scale_last_layer = 0.01


[admm_affine_20]
# ========================================
# 1. Global Training Params
# ========================================
batch_size = 20
epochs = 30
warming_iters = 10
n_timesteps = 150

# ========================================
# 2. Shared Params
# ========================================

deltas = 0.99 
thetas = 0.15

# ========================================
# 3. Linear Params
# ========================================
hidden_dims=516
linear_gamma = 0.01
linear_beta = 0.01

linear_scale = 1.0
linear_scale_last_layer = 0.01


# ========================================
# 4. Conv Params
# ========================================
hidden_channels=16

conv_gamma = 0.01
conv_beta = 0.01

conv_scale = 3.0
conv_scale_last_layer = 0.01
