[static]
model= spiking-conv
batch_size = 50
epochs = 20
warming_iters = 6
gamma = 0.1
beta = 1.0
n_timesteps = 150
deltas = 0.95
thetas = 0.3
hidden_dims=100
hidden_channels=4
kernel_size=5
padding=2
stride=2
; init = zeros
bias=False 
; train_method = unrolled-sequential
use_double=False

[grid]
; model= spiking-conv
; batch_size = 50
; epochs = 20
; warming_iters = 6
; gamma = 0.1
; beta = 1.0
; n_timesteps = 150
; deltas = 0.95
; thetas = 0.3
; hidden_dims=100
; hidden_channels=4
; kernel_size=5
; padding=2
; stride=2
init = zeros, xavier
; bias=False 
train_method = unrolled-sequential, unrolled-random
; use_double=False