[static]
model= spiking-conv
batch_size = 30
epochs = 50
warming_iters = 15
beta = 0.1
rho = 1.0
n_timesteps = 150
deltas = 0.95
thetas = 0.3
hidden_dims=100
hidden_channels=2
kernel_size=5
padding=2
stride=1
init = zeros
bias=False 
train_method = unrolled-random
use_double=False
; layers=2

[grid]
model= spiking-conv
; batch_size = 50, 100
; epochs = 20
; warming_iters = 6
; beta = 0.1
; rho = 1.0
; n_timesteps = 150
; deltas = 0.95
; thetas = 0.3
; hidden_dims=100
; hidden_channels=4
; kernel_size=5
; padding=2
; stride=2
; init = zeros, xavier
; bias=False 
; train_method = unrolled-random
; use_double=False
layers=3,2