[config]
seed= 8281003564
#OPTIONS ARE: linear, conv, spiking-linear, spiking-conv
model = linear
#OPTIONS ARE: 2,3 (For non spiking also 5)
layers = 2

batch_size = 60000
epochs = 100
warming_iters = 11

beta = 0.1
rho = 0.1

n_timesteps = 150
deltas = 0.95
thetas = 1
hidden_dims = 1000

hidden_channels = 2
kernel_size = 1
padding = 0
stride = 1

#RECOMENDATION: s-uniform for spiking and pytorch for static
init = pytorch
#OPTIONS ARE: "vectorized", "unrolled-random", "unrolled-sequential", "decoupled-random", "decoupled-sequential"
train_method =  vectorized

bias = True
use_double = False
use_fft = True
padding_mode = zeros
